### ISSUE TITLE
Rebuild image to update rclone

### ISSUE THREAD

**Issue by MartinSadovy** [instrumentisto/restic-docker-image#12]
last image contains: rclone v1.58.1-DEV

rclone contains 1.59.x contains new storage providers https://rclone.org/changelog/

**Comment by tyranron** [comment]
@MartinSadovy rebuilding the image won't help, as the Alpine repos for 3.16 still contains 1.58.

https://pkgs.alpinelinux.org/packages?name=rclone&branch=v3.16

**Comment by MartinSadovy** [comment]
thanks for response. I looked at edge, you are right. So we are waiting...

**Comment by MartinSadovy** [comment]
Good news everyone! new 3.17 contains 1.60.x

https://pkgs.alpinelinux.org/packages?name=rclone&branch=v3.17&repo=&arch=&maintainer=

**Comment by tyranron** [comment]
@MartinSadovy yup, just was waiting until [`golang` image](https://github.com/docker-library/golang/pull/442) will keep up. Will release tomorrow.

**Comment by tyranron** [comment]
Released in [0.14.0-r1](https://github.com/instrumentisto/restic-docker-image/releases/tag/0.14.0-r1).
