### ISSUE TITLE
What does this add/change compared to the official restic docker image?

### ISSUE THREAD

**Issue by mrmachine** [instrumentisto/restic-docker-image#5]
It's not obvious that there are any additional or changed features from the README?

**Comment by stephane-klein** [comment]
@tyranron 🙏

**Comment by tyranron** [comment]
@mrmachine @stephane-klein the main difference is that this image [also contains `rclone`](https://github.com/instrumentisto/restic-docker-image/blob/0.9.6/Dockerfile#L20-L23).

Another difference is that any built tag can be reproduced, as compilation happens from sources inside `Dockerfile`, while [official image just copies a binary pre-built elsewhere](https://github.com/restic/restic/blob/v0.9.6/docker/Dockerfile#L3).

And the most important one for me, is that this image has [convenient versioning](https://github.com/instrumentisto/restic-docker-image/tree/0.9.6#image-versions), while official image has [exact versions only](https://hub.docker.com/r/restic/restic/tags). This is crucial, as I have to deal with a lot of software and Docker images at my job. And playing around just with every single patch version just eats my time with no benefit. As with programming languages package managers, it's much more convenient to apply version range and bother only if BC breaks happens or new interesting features has been arrived.

**Comment by tyranron** [comment]
There is also [some background about merging this work into official image](https://github.com/restic/restic/issues/931#issuecomment-368790852), but I haven't received any news from the author after that.

**Comment by kgnfth** [comment]
https://github.com/djmaze/resticker/ is better
