### ISSUE TITLE
How to setup rclone

### ISSUE THREAD

**Issue by zwnk** [instrumentisto/restic-docker-image#7]
Hi there,

what would be the best way to supply a rclone config?
somehting like `-v /rcloneconf_local/:/rcloneconf/ -e RCLONE_CONFIG=/rcloneconf/rclone.conf` ?

Cheers

**Comment by tyranron** [comment]
@zwnk I guess, yes. Just mount it and go ahead.

**Comment by zwnk** [comment]
It works like mentioned. Thanks!

**Comment by zwnk** [comment]
Sorry, i was to fast. I did not check if i'm able to push the actual backup.
So it looks like `init` does something, but definitly not on the onedrive. Don't know where the actual repo is initialized, but when i do `backup` it throws an error that the config is not found:

```
/:/rcloneconf/ -e RCLONE_CONFIG=/rcloneconf/rclone.conf instrumentisto/restic backup /fotos
Fatal: unable to open config file: <config/> does not exist
Is there a repository at the following location?
rclone:remote2
```

but in the given location there is a rclone.con with a remote2 defined.

**Comment by tyranron** [comment]
@zwnk well, you may debug by running something like this:
```bash
docker run --rm -it -v /rcloneconf_local/:/rcloneconf/ -e RCLONE_CONFIG=/rcloneconf/rclone.conf --entrypoint sh instrumentisto/restic
> ls -l /rcloneconf/
```
It seems that there is something wrong with your mounting from the host.

**Comment by zwnk** [comment]
after checking the `env` and the path were correct i found the issue by comparing the `rclone:remote` string to another native install i'm running.
It seems you have to define a subfolder for the onedrive so the `-e RESTIC_REPOSITORY` has to be like this `-e RESTIC_REPOSITORY=rclone:remote:backup`.

thank you for taking your time to explain how to debug.
